package com.BarcelonaSC.BarcelonaApp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NOTIFICATION_SETTING".
 */
@SuppressWarnings("ALL")
@Entity
public class NotificationSetting {

    @Id(autoincrement = true)
    @Unique
    private long id;
    private String topic;
    private Boolean status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public NotificationSetting() {
    }

    public NotificationSetting(long id) {
        this.id = id;
    }

    @Generated
    public NotificationSetting(long id, String topic, Boolean status) {
        this.id = id;
        this.topic = topic;
        this.status = status;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
