package com.BarcelonaSC.BarcelonaApp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTIFICATION_SETTING".
*/
public class NotificationSettingDao extends AbstractDao<NotificationSetting, Long> {

    public static final String TABLENAME = "NOTIFICATION_SETTING";

    /**
     * Properties of entity NotificationSetting.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Topic = new Property(1, String.class, "topic", false, "TOPIC");
        public final static Property Status = new Property(2, Boolean.class, "status", false, "STATUS");
    }


    public NotificationSettingDao(DaoConfig config) {
        super(config);
    }
    
    public NotificationSettingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTIFICATION_SETTING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE ," + // 0: id
                "\"TOPIC\" TEXT," + // 1: topic
                "\"STATUS\" INTEGER);"); // 2: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTIFICATION_SETTING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NotificationSetting entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String topic = entity.getTopic();
        if (topic != null) {
            stmt.bindString(2, topic);
        }
 
        Boolean status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(3, status ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NotificationSetting entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String topic = entity.getTopic();
        if (topic != null) {
            stmt.bindString(2, topic);
        }
 
        Boolean status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(3, status ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public NotificationSetting readEntity(Cursor cursor, int offset) {
        NotificationSetting entity = new NotificationSetting( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // topic
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0 // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NotificationSetting entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTopic(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStatus(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NotificationSetting entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NotificationSetting entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NotificationSetting entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
