package com.millonarios.MillonariosFC.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.millonarios.MillonariosFC.db.NotificationSetting;

import com.millonarios.MillonariosFC.db.NotificationSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notificationSettingDaoConfig;

    private final NotificationSettingDao notificationSettingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notificationSettingDaoConfig = daoConfigMap.get(NotificationSettingDao.class).clone();
        notificationSettingDaoConfig.initIdentityScope(type);

        notificationSettingDao = new NotificationSettingDao(notificationSettingDaoConfig, this);

        registerDao(NotificationSetting.class, notificationSettingDao);
    }
    
    public void clear() {
        notificationSettingDaoConfig.clearIdentityScope();
    }

    public NotificationSettingDao getNotificationSettingDao() {
        return notificationSettingDao;
    }

}
